sudo: required
language: go
go:
  - "1.10"
# needed for the docker pipe
services:
- docker
install:
- go get -u github.com/constabulary/gb/...
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install
# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    
after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
