version: '3'
services:
  prometheus-telegram-bot:
    image: jieht9u/prometheus-telegram-bot:1.0.3
    hostname: prometheus-telegram-bot
    # restart: always
    ports:
      - "9087:9087"
    command: ["--telegram-token=${TELEGRAM_BOT_TOKEN}","--template-paths=/home/project/go/prometheus-telegram-bot/template/*.tmpl" ]